name: web_extensions
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: downloading <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  logging: any

dev_dependencies:
  test: ^1.0.0
